* Bdu-Thesis-Latex-Package
A Latex Package for writing a masters thesis according to Bahirdar University guideline.
It has the following features:
- sets the typing according to the recommended format. This includes margins, font, linespacing, etc...
- has all the neccessary front matter. cover page, title page, declaration page, approval sheet, acknowledgment.

* Installation
For linux, mac or using wsp on windows.

#+begin_src shell
  git clone https://github.com/Nathan-Melaku/Bdu-Thesis-Latex-Package.git
#+end_src

or download and unzip this repository. Then copy the files in this repository to your thesis directory.

* Usage
xelatex must be used to compile your project for this package to work properly. This is due to the usage of =Times New Roman= Font.
The package introduces the following commands:

1. *\advisor{name of advisor}{title of advisor}:* used for defining the name and title of advisor.
2. *\coadvisor{name of coadvisor}{title of coadvisor}:* used for defining the name and title of coadvisor.
   If it doesn't apply you can ignore this.
3. *\faculty{name of faculty}:* used for defining the name of the faculty. eg. Electrical and Computer Engineering.
4. *\program{name of the program}:* used for defining the name of the program. eg. Computer Engineering.
5. *\masterstype{Type of Masters}:* used for defining the type of masters there are two types Msc thesis or MEng Project.
6. *\acknowledgment{text}:* used for defining the acknowledgment.
7. *\abstract{text}:* used for defining the abstract.
8. *\makepreamble:* used for printing the preamble necessary according to the guideline.

A simple Makefile have been prepared. In order for it to work you need a file hierarchy according to the following schema.
#+begin_src ditaa
  ROOT
  |
  +---Images
  |       |
  |       +---logo.jpg
  |       |
  |       +---Other images
  |
  +---Chapters
  |       |
  |       +---put chapters here
  |
  +---references.bib
  |
  +---main.tex
#+end_src

Use the [[https://ctan.org/pkg/subfiles?lang=en][subfiles]] package to insert the your chapters into the main file. Then set main.tex as
a master file for compilation in your editor. For use auctex mode and add the following at the end of each chapter tex file.

#+begin_src latex
%%% Local Variables:
%%% mode: latex
%%% TeX-master: "../main"
%%% End:
#+end_src
