* Bdu-Thesis-Latex-Package
A Latex Package for writing a masters thesis according to Bahirdar Bahir Dar Institute of Technology guideline.
It has the following features:
- sets the typing according to the recommended format. This includes margins, font, linespacing, etc...
- has all the neccessary front matter. cover page, title page, declaration page, approval sheet, acknowledgment.
- enforces the appropriate citation format.

* Installation
For linux, mac or using wsp on windows.

#+begin_src shell
  git clone https://github.com/Nathan-Melaku/Bdu-Thesis-Latex-Package.git
#+end_src

or download and unzip this repository. Then copy the files in this repository to your thesis directory.
Then bduMasters as a documentclass.

#+begin_src latex
  \documentclass{bduMasters}

  % put the packages you need

  \adnnvisor{awesome advisor}{PHD}
  \faculty{Electrical and Computer Engineering}
  \program{Computer Engineering}
  \masterstype{Msc Thesis}
  \title{My awesome title}
  \author{My awesome name}
  \date{\today}

  \acknowledgment{My awesome acknowledgment}
  \abstract{My awesome abstract}

  \begin{document}
  \makepreamble
  \pagenumbering{arabic}

  % put your chapters
  \subfile{Chapters/introduction}
  ...
  \end{document}
#+end_src

* Usage
xelatex must be used to compile your project for this package to work properly. This is due to the usage of =Times New Roman= Font.
The package introduces the following commands:

1. *\advisor{name of advisor}{title of advisor}:* used for defining the name and title of advisor.
2. *\coadvisor{name of coadvisor}{title of coadvisor}:* used for defining the name and title of coadvisor.
   If it doesn't apply for you can ignore this.
3. *\faculty{name of faculty}:* used for defining the name of the faculty. eg. Electrical and Computer Engineering.
4. *\program{name of the program}:* used for defining the name of the program. eg. Computer Engineering.
5. *\masterstype{Type of Masters}:* used for defining the type of masters there are two types Msc thesis or MEng Project.
6. *\acknowledgment{text}:* used for defining the acknowledgment.
7. *\abstract{text}:* used for defining the abstract.
8. *\makepreamble:* used for printing the preamble necessary according to the guideline. This will handle everything from
   coverpage to abstract. After this command set the page numbering style and add your chapters. That is all.

A simple Makefile have been prepared. In order for it to work you need a file hierarchy according to the following schema.
#+begin_src ditaa
  ROOT
  |
  +---Images
  |       |
  |       +---logo.jpg
  |       |
  |       +---Other images
  |
  +---Chapters
  |       |
  |       +---put chapters here
  |
  +---references.bib
  |
  +---main.tex
  |
  +---acronym.tex
#+end_src

Use the [[https://ctan.org/pkg/subfiles?lang=en][subfiles]] package to insert your chapters into the main file. Then set main.tex as
a master file for compilation in your editor. For Emacs use auctex mode and add the following at the end of each chapter tex file.

#+begin_src latex
%%% Local Variables:
%%% mode: latex
%%% TeX-master: "../main"
%%% End:
#+end_src

Define abbreviations in acronym.tex file. A sample is provided.

#+begin_src latex
  \acro{GAN}{Generative Adversarial Networks}
#+end_src

Then use it in the document. Do not use abbreviations in Abstract. A sample usage is as follows.

#+begin_src latex
  a sample usage \ac{GAN}.
#+end_src

An example file can be found in this repository. Check out [[file:main.tex][main.tex]], [[file:acronym.tex][acronym.tex]] and the associated chapters in the [[file:Chapters/][Chapters]] directory.

* LICENSE

BSD 2-Clause License

Copyright (c) 2022, Nathan Melaku Abeje
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
